### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by berdoff** [CoreTaxxe/AsyncIRCClient#1]
can u add use proxy?

**Comment by CoreTaxxe** [comment]
Hi there,
I've added basic proxy support. Note that this isn't thoroughly tested so please report any issues you encounter :D
Also, some Proxies do not like IRC connections and will not work reliably.

Usage:
```py
    from async_irc_client import Proxy, ProxyType

    MyBot(
        oauth_token="YOURTOKEN",
        nick_name="BOTNAME",
        channel="CHANNELNAME",
        proxies=[
            Proxy(ProxyType.HTTP, "ip", 1234),
            Proxy(ProxyType.HTTP, "ip", 1234, password="password", username="username"),
            Proxy.from_url("proxy_url")
        ]
    ).run()
```

**Comment by berdoff** [comment]
after connect crash and

python_socks._errors.ProxyError: Invalid status line: [

**Comment by berdoff** [comment]
fix this, thx <3

**Comment by berdoff** [comment]
one more problem

WARNING  | async_irc_client.async_irc_client:_on_protocol_data_received:1033 - Invalid command: Callback not found for: PART

**Comment by CoreTaxxe** [comment]
> after connect crash and
> 
> python_socks._errors.ProxyError: Invalid status line: [

I cannot replicate this issue. Could you provide some code?

Also PART is added now. Generally, this warning can be ignored as it just skips the PART (Leave) Event.

**Comment by berdoff** [comment]
all work, thx<3

**Comment by berdoff** [comment]
ohh,  i need new feature, sorry(
Can u add stop function to stop bot(stop loops and tasks and close connection)

for example



    
```
class MyBot(TwitchIRCBot):
    async def on_client_ready(self, message: Message) -> None:
        self.stop()
bot=MyBot(...)
bot.run()
```

**Comment by berdoff** [comment]
thx

**Comment by CoreTaxxe** [comment]
Welcome :D

**Comment by berdoff** [comment]
one problem( AttributeError: 'MyBot' object has no attribute 'stop'

**Comment by CoreTaxxe** [comment]
If you installed via PyPI it may be that it hasnt updated the package yet.

try `pip install AsyncIRCClient==0.1.2`

**Comment by berdoff** [comment]
stop()
crush application
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
asyncio.exceptions.CancelledError

**Comment by CoreTaxxe** [comment]
Couldn't reproduce but I've added try-except statements to catch the errors.

**Comment by berdoff** [comment]
[2024-02-22 15:43:07 +0300] [712993] [INFO] Error while closing socket [Errno 9] Bad file descriptor

**Comment by berdoff** [comment]
that bug is asyncirc or gunicorn?)

**Comment by CoreTaxxe** [comment]
If you are using proxies then its probably an issue in `python-socks`. If not could you provide more details as to where it exactly happens? (For example is it caused by a `transport.close()` call?)
